#!/bin/bash

home=/ccs/home/cql0536/exageostat_parsec

#cmake $home -DCMAKE_CXX_COMPILER=xlC_r -DCMAKE_C_COMPILER=xlc_r -DCMAKE_Fortran_COMPILER=xlf_r -DCMAKE_INSTALL_PREFIX=$PWD/install_dir -DCMAKE_COLOR_MAKEFILE:BOOL=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_SHARED_LIBS=OFF -DEXAGEOSTAT_USE_HICMA=OFF -DEXAGEOSTAT_USE_NETCDF=ON -DEXAGEOSTAT_USE_MPI=ON -DEXAGEOSTAT_USE_CUDA=OFF -DCMAKE_BUILD_TYPE=Release -DEXAGEOSTAT_USE_DPLASMA=ON -DBLAS_LIBRARIES="${OLCF_ESSL_ROOT}/lib64/libessl.so" -DBLAS_COMPILER_FLAGS="-I${OLCF_ESSL_ROOT}/include" -DCBLAS_DIR="${LAPACKE_ROOT}" -DLAPACKE_DIR="${LAPACKE_ROOT}" -DLAPACK_LIBRARIES="-L${LAPACKE_ROOT}/lib;-llapack" -DEXAGEOSTAT_ON_SUMMIT=ON

cmake $home -DCMAKE_CXX_COMPILER=mpic++ -DCMAKE_C_COMPILER=mpicc -DCMAKE_Fortran_COMPILER=mpif90 -DCMAKE_INSTALL_PREFIX=$PWD/install_dir -DEXAGEOSTAT_USE_HICMA=OFF -DEXAGEOSTAT_USE_NETCDF=ON -DEXAGEOSTAT_USE_CUDA=OFF -DEXAGEOSTAT_USE_DPLASMA=ON -DBLAS_LIBRARIES="${OLCF_ESSL_ROOT}/lib64/libessl.so" -DBLAS_COMPILER_FLAGS="-I${OLCF_ESSL_ROOT}/include" -DCBLAS_DIR="${LAPACKE_ROOT}" -DLAPACKE_DIR="${LAPACKE_ROOT}" -DLAPACK_LIBRARIES="-L${LAPACKE_ROOT}/lib;-llapack" -DEXAGEOSTAT_ON_SUMMIT=ON -DEXAGEOSTAT_SCHED_STARPU=ON -DEXAGEOSTAT_USE_MPI=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS_RELEASE="-O3 -qmaxmem=-1"
